const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../../..'),base=path.join(root,'.cache/installation-tests',String(Date.now()));
test('Codex installation selection and targeted update',async t=>{
 await fs.mkdir(base,{recursive:true});
 for(const name of ['WindowsShimAdapter','RuntimeCommandRunner','NpmInstallationInspector','CodexInstallationRepository','CodexInstallationService','CodexRuntimeStateRepository','CodexRuntimeStateService','CodexUpdateService','CodexRuntimeProbe'])await fs.writeFile(path.join(base,name+'.js'),ts.transpileModule(await fs.readFile(path.join(root,'apps/desktop/src/main/runtime/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText);
 await fs.writeFile(path.join(base,'presentation.js'),ts.transpileModule(await fs.readFile(path.join(root,'apps/desktop/src/renderer/components/settings/runtimePresentation.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);
 const {CodexInstallationService:Installations,validateCandidateId}=require(path.join(base,'CodexInstallationService.js'));
 const {CodexInstallationRepository:Repository}=require(path.join(base,'CodexInstallationRepository.js'));
 const {CodexRuntimeStateRepository:StateRepository}=require(path.join(base,'CodexRuntimeStateRepository.js'));
 const {CodexRuntimeStateService:StateService}=require(path.join(base,'CodexRuntimeStateService.js'));
 const {RuntimeCommandRunner:Runner}=require(path.join(base,'RuntimeCommandRunner.js'));
 const {CodexRuntimeProbe:Probe}=require(path.join(base,'CodexRuntimeProbe.js'));
 const {CodexUpdateService:Updater}=require(path.join(base,'CodexUpdateService.js'));
 const {owningNpmPrefix}=require(path.join(base,'NpmInstallationInspector.js'));
 const {runtimePresentation:present}=require(path.join(base,'presentation.js'));
 let serial=0;
 async function fixture(count=2){
  const dir=path.join(base,'fixture-'+(++serial));await fs.mkdir(dir,{recursive:true});const codex=[];const versions=new Map();const calls=[];
  for(let i=0;i<count;i++){const prefix=path.join(dir,'install-'+i);await fs.mkdir(prefix,{recursive:true});const exe=path.join(prefix,process.platform==='win32'?'codex.exe':'codex');await fs.writeFile(exe,Buffer.from([0x4d,0x5a,0,0]));codex.push(exe);versions.set(exe,i===0?'0.151.0':'0.154.0-alpha.6.2');}
  let paths=[...codex];const runner={resolveAll:async tool=>tool==='codex'?[...paths]:[],run:async(file,command)=>{calls.push({file,command});return{stdout:'codex-cli '+versions.get(file)+'\n',exitCode:0,failed:false,timedOut:false}}};
  const store=new Repository(path.join(dir,'selection.json'));const make=()=>new Installations(store,runner);const installations=make();
  const health={refresh:async()=>({runtime:'codex',status:'ready',version:'0.151.0',authenticationMethod:'ChatGPT',checkedAt:new Date().toISOString()}),invalidate:()=>{}};
  let verifies=0;const verifier={run:async()=>{verifies++;return{status:'passed',response:'Hello from Flux.',verificationReason:null,checkedAt:new Date().toISOString()}},shutdown:async()=>{}};
  const service=new StateService(new StateRepository(path.join(dir,'state.json')),health,verifier,{update:async()=>null,shutdown:async()=>{}},installations);
  return{dir,codex,versions,calls,runner,store,make,installations,service,health,verifier,verifies:()=>verifies,setPaths:value=>paths=value};
 }
 await t.test('one verified candidate is used without a selection screen',async()=>{const f=await fixture(1);assert.equal((await f.installations.inspect()).selectionRequired,false);assert.equal(await f.installations.resolve(),f.codex[0]);assert.ok((await f.store.load()).selectedCandidateId)});
 await t.test('two candidates require selection before health/model verification; only Choose installation is shown',async()=>{const f=await fixture();const result=await f.service.inspect();assert.equal(result.state.operationalStatus,'INSTALLATION_SELECTION_REQUIRED');assert.equal(f.verifies(),0);assert.equal(await f.installations.resolve(),null);const view=present(result);assert.equal(view.label,'Setup required');assert.equal(view.canChoose,true);assert.equal(view.canUpdate,false);assert.equal(view.canRetry,false);assert.equal(view.detail,null)});
 await t.test('dialog candidates have versions and badges but no implicit selected radio',async()=>{const f=await fixture();const list=await f.installations.list();assert.equal(list.length,2);assert.equal(list[1].version,'0.154.0-alpha.6.2');assert.equal(list[0].isFirstOnPath,true);assert.ok(list.every(c=>!c.isCurrentlySelected));const source=await fs.readFile(path.join(root,'apps/desktop/src/renderer/components/settings/CodexInstallationDialog.tsx'),'utf8');assert.ok(source.includes('useState<string | null>(null)'));assert.ok(!source.includes('type="text"'))});
 await t.test('renderer input must be an allowlisted id, never a path, object or fabricated id',async()=>{const f=await fixture();await f.installations.list();for(const bad of [f.codex[0],{id:'a'.repeat(64)},null,'a'.repeat(64)])await assert.rejects(f.installations.choose(bad));assert.throws(()=>validateCandidateId('cmd /c unsafe'));assert.equal(await f.store.load(),null)});
 await t.test('candidate removed after listing is rejected without execution',async()=>{const f=await fixture();const list=await f.installations.list();await fs.unlink(f.codex[0]);f.calls.length=0;await assert.rejects(f.installations.choose(list[0].id));assert.equal(f.calls.length,0)});
 await t.test('selection survives transitions, restart, PATH reordering and absence from PATH',async()=>{const f=await fixture();const list=await f.installations.list();await f.installations.choose(list[1].id);f.setPaths([f.codex[1],f.codex[0]]);assert.equal(await f.installations.resolve(),f.codex[1]);const restarted=f.make();assert.equal((await restarted.inspect()).selectionRequired,false);assert.equal(await restarted.resolve(),f.codex[1]);f.setPaths([f.codex[0]]);assert.equal(await restarted.resolve(),f.codex[1]);const after=await restarted.list();assert.equal(after.find(c=>c.id===list[1].id).isFirstOnPath,false);assert.equal(after.find(c=>c.id===list[1].id).isCurrentlySelected,true)});
 await t.test('removed selected executable never falls back, including after restart with one candidate left',async()=>{const f=await fixture();const list=await f.installations.list();await f.installations.choose(list[0].id);await fs.unlink(f.codex[0]);f.setPaths([f.codex[1]]);assert.equal(await f.installations.resolve(),null);assert.equal((await f.installations.inspect()).selectionRequired,true);assert.equal((await f.make().inspect()).selectionRequired,true);assert.equal(await f.make().resolve(),null)});
 await t.test('replaced non-Codex file is rejected before executing it',async()=>{const f=await fixture();const list=await f.installations.list();await f.installations.choose(list[0].id);await fs.writeFile(f.codex[0],'not an executable');f.calls.length=0;assert.equal(await f.installations.resolve(),null);assert.equal(f.calls.length,0)});
 await t.test('health and App Server source resolve the same selected executable, not the first PATH candidate',async()=>{const f=await fixture();const list=await f.installations.list();await f.installations.choose(list[1].id);const bound=new Runner(()=>f.installations.resolve());const commands=[];bound.run=async(file,command)=>{commands.push({file,command});return {stdout:command==='version'?'codex-cli 0.154.0-alpha.6.2':'Logged in using ChatGPT',stderr:'',exitCode:0,failed:false,timedOut:false}};assert.equal((await new Probe(bound).check()).status,'ready');const appServerPath=await bound.resolveCodex();assert.ok(commands.every(c=>c.file===appServerPath));assert.equal(appServerPath,f.codex[1]);const clientSource=await fs.readFile(path.join(root,'apps/desktop/src/main/app-server/CodexAppServerClient.ts'),'utf8');assert.ok(clientSource.includes('await runner.resolveCodex()'))});
 await t.test('selection invalidates old verification, and bad hello cannot become Ready',async()=>{const f=await fixture();await f.service.inspect();const list=await f.service.candidates();f.verifier.run=async()=>({status:'passed',response:'wrong',verificationReason:null,checkedAt:new Date().toISOString()});const result=await f.service.selectInstallation(list[0].id);assert.equal(result.state.operationalStatus,'VERIFICATION_FAILED');assert.equal(result.state.verificationStatus,'failed')});
 await t.test('invalid selection does not leave activity busy',async()=>{const f=await fixture();await f.service.inspect();await assert.rejects(f.service.selectInstallation('a'.repeat(64)));assert.equal(f.service.snapshot().activity,null)});
 await t.test('standalone cannot update and offers Choose another installation',async()=>{const f=await fixture();const list=await f.installations.list();await f.installations.choose(list[0].id);assert.equal(await f.installations.updateTarget(),null);let launched=false;const update=new Updater({startNpmUpdate:()=>{launched=true}},f.installations);assert.equal(await update.update(),'UNKNOWN_INSTALLATION');assert.equal(launched,false);const view=present({state:{operationalStatus:'UPDATE_REQUIRED',verificationReason:'CLI_TOO_OLD'},activity:null,installation:f.installations.currentSummary()});assert.equal(view.canUpdate,false);assert.equal(view.canChoose,true);assert.equal(view.chooseLabel,'Choose another installation')});
 await t.test('npm ownership targets only selected prefix and rejects a mismatched package',async()=>{
  const f=await fixture(0);const prefix=path.join(f.dir,'npm prefix with spaces');const pkg=path.join(prefix,process.platform==='win32'?'node_modules':'lib/node_modules','@openai/codex');await fs.mkdir(path.join(pkg,'bin'),{recursive:true});await fs.writeFile(path.join(pkg,'package.json'),JSON.stringify({name:'@openai/codex',bin:{codex:'bin/codex.js'}}));await fs.writeFile(path.join(pkg,'bin/codex.js'),'');const exe=process.platform==='win32'?path.join(prefix,'codex.cmd'):path.join(prefix,'bin/codex');if(process.platform==='win32')await fs.writeFile(exe,'node_modules\\@openai\\codex\\bin\\codex.js');else {await fs.mkdir(path.dirname(exe),{recursive:true});await fs.symlink(path.join(pkg,'bin/codex.js'),exe)}
  assert.equal(await owningNpmPrefix(exe),await fs.realpath(prefix));await fs.writeFile(path.join(pkg,'package.json'),JSON.stringify({name:'wrong',bin:{codex:'bin/codex.js'}}));assert.equal(await owningNpmPrefix(exe),null);
 });
 await t.test('selected update uses targeted runner without any global PATH fallback',async()=>{
  const {EventEmitter}=require('node:events'),{PassThrough}=require('node:stream');const child=new EventEmitter();child.stdin=new PassThrough();child.stdout=new PassThrough();child.stderr=new PassThrough();const target={prefix:path.join(base,'chosen-prefix'),nodeExecutable:'validated-node',npmCli:'validated-cli'};let used;
  const runner={startNpmUpdate:value=>{used=value;setImmediate(()=>child.emit('close',0));return child},resolveAll:()=>{throw Error('No PATH fallback allowed')}};
  const updater=new Updater(runner,{updateTarget:async()=>target});assert.equal(await updater.update(),null);assert.deepEqual(used,target);assert.equal(child.listenerCount('close'),0);
  const source=await fs.readFile(path.join(root,'apps/desktop/src/main/runtime/RuntimeCommandRunner.ts'),'utf8');assert.ok(source.includes("'--prefix', target.prefix, '@openai/codex@latest'"));assert.ok(source.includes('shell: false'));
 });
 await t.test('target prefix remains one argv value with spaces and shell metacharacters',async()=>{
  const prefix=path.join(base,'prefix with spaces & percent%');await fs.mkdir(prefix,{recursive:true});const npmCli=path.join(base,'npm-cli.js');await fs.writeFile(npmCli,'process.stdout.write(JSON.stringify(process.argv.slice(2)));');
  const runner=new Runner();const child=runner.startNpmUpdate({prefix,nodeExecutable:process.execPath,npmCli});child.stdin.end();let output='';child.stdout.on('data',b=>output+=b);const exit=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('close',resolve)});assert.equal(exit,0);assert.deepEqual(JSON.parse(output),['install','--global','--prefix',prefix,'@openai/codex@latest']);
 });
});
