const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const ts = require('typescript');
const root = path.resolve(__dirname, '../../..');
const base = path.join(root, '.cache/project-service-tests', String(Date.now()));
const git = (dir, ...args) => execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8', windowsHide: true }).trim();

test('project authorization, local branches, persistence and read-only selection', async () => {
  await fs.mkdir(base, { recursive: true });
  for (const name of ['ProjectError', 'project-path', 'GitRepositoryService', 'ProjectRepository', 'ProjectService']) {
    const source = await fs.readFile(path.join(root, 'apps/desktop/src/main/projects', name + '.ts'), 'utf8');
    const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } });
    await fs.writeFile(path.join(base, name + '.js'), output.outputText);
  }
  const { ProjectRepository } = require(path.join(base, 'ProjectRepository.js'));
  const { GitRepositoryService } = require(path.join(base, 'GitRepositoryService.js'));
  const { ProjectService } = require(path.join(base, 'ProjectService.js'));
  const registry = path.join(base, 'projects.json');
  const service = new ProjectService(new ProjectRepository(registry), new GitRepositoryService(), root);
  const initial = await service.getProjects();
  assert.equal(initial.length, 1);
  assert.equal(initial[0].selectedBranch, git(root, 'branch', '--show-current'));
  await assert.rejects(service.addProject(root.toUpperCase() + '\\'), { code: 'DUPLICATE_PROJECT' });
  await assert.rejects(service.getGitBranches(path.join(base, 'unauthorized')), { code: 'PATH_NOT_AUTHORIZED' });
  await assert.rejects(service.addProject(path.join(base, 'unauthorized')), { code: 'PATH_NOT_AUTHORIZED' });
  const invalid = path.join(base, 'not-a-repo');
  await fs.mkdir(invalid);
  await service.authorizeDirectory(invalid);
  await assert.rejects(service.addProject(invalid), { message: 'The selected folder is not a Git repository.' });
  const fixture = path.join(base, 'fixture-repo');
  await fs.mkdir(fixture);
  git(fixture, 'init', '--initial-branch=fixture-main');
  await service.authorizeDirectory(fixture);
  await assert.rejects(service.addProject(fixture), { code: 'NO_LOCAL_BRANCHES' });
  git(fixture, 'fetch', '--no-tags', root, 'HEAD');
  git(fixture, 'update-ref', 'refs/heads/fixture-main', 'FETCH_HEAD');
  git(fixture, 'update-ref', 'refs/heads/feature-preview', 'FETCH_HEAD');
  git(fixture, 'update-ref', 'refs/remotes/origin/remote-only', 'FETCH_HEAD');
  const added = await service.addProject(fixture);
  assert.equal(added.selectedBranch, 'fixture-main');
  assert.deepEqual(await service.getGitBranches(fixture), ['feature-preview', 'fixture-main']);
  const head = git(fixture, 'symbolic-ref', 'HEAD');
  const status = git(fixture, 'status', '--porcelain');
  await service.selectWorkspace(added.id, 'feature-preview');
  assert.equal(git(fixture, 'symbolic-ref', 'HEAD'), head);
  assert.equal(git(fixture, 'status', '--porcelain'), status);
  await assert.rejects(service.selectWorkspace(added.id, 'remote-only'), { code: 'BRANCH_NOT_FOUND' });
  await assert.rejects(service.addProject(fixture), { code: 'DUPLICATE_PROJECT' });
  const reopened = new ProjectService(new ProjectRepository(registry), new GitRepositoryService(), root);
  assert.equal((await reopened.getProjects())[0].selectedBranch, 'feature-preview');
  assert.equal((await reopened.getProjects())[0].id, added.id);
  assert.equal(await reopened.getCurrentBranch(fixture), 'fixture-main');
  await Promise.all([reopened.selectWorkspace(added.id, 'fixture-main'), reopened.selectWorkspace(initial[0].id, initial[0].selectedBranch)]);
  assert.equal((await reopened.getProjects()).length, 2);
  const corrupt = path.join(base, 'corrupt.json');
  await fs.writeFile(corrupt, 'broken');
  await assert.rejects(new ProjectRepository(corrupt).list(), { code: 'REGISTRY_INVALID' });
  assert.equal(await fs.readFile(corrupt, 'utf8'), 'broken');
  await fs.writeFile(path.join(root, '.cache/project-fixture.json'), JSON.stringify({ fixture, invalid }));
});
