const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),ts=require('typescript');
test('Confirmed online workspace preparation',async t=>{
 const parent=path.resolve('.cache/online-tests');await fs.mkdir(parent,{recursive:true});const base=await fs.mkdtemp(path.join(parent,'case-'));t.after(()=>fs.rm(base,{recursive:true,force:true}));
 async function compile(dir){for(const e of await fs.readdir('apps/desktop/src/'+dir,{withFileTypes:true})){const f=dir+'/'+e.name;if(e.isDirectory())await compile(f);else if(f.endsWith('.ts')&&!f.endsWith('.d.ts')){const out=path.join(base,f.replace(/\.ts$/,'.js'));await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,ts.transpileModule(await fs.readFile('apps/desktop/src/'+f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)}}}
 for(const dir of ['application/environment','main/environment','main/persistence','main/projects','shared'])await compile(dir);
 const load=name=>require(path.join(base,name));
 const {WorkspaceEnvironmentRegistry}=load('application/environment/WorkspaceEnvironmentProvider'),{WorkspaceEnvironmentService,onlineRequest}=load('application/environment/WorkspaceEnvironmentService');
 const {allowedRegistry,safeDownloadCode,validateLockfileDownloads}=load('main/environment/PnpmRegistry'),{PnpmOfflineProvider,onlineInstallArgs}=load('main/environment/PnpmOfflineProvider');
 const {validatePnpmWorkspace}=load('main/environment/PnpmWorkspaceValidation');
 const {JsonWorkspaceEnvironmentStore}=load('main/environment/WorkspaceEnvironmentStore'),{EnvironmentProcess,isolatedEnvironment}=load('main/environment/EnvironmentProcess');
 const runId='a55379cf-e01a-49b1-9b14-c89623ff82e7',consentId='b2c3ce40-3c44-4b7e-a819-719016f891a4',context={runId,workspaceId:runId,directory:path.join(base,'workspace')};
 await fs.mkdir(path.join(context.directory,'apps/desktop'),{recursive:true});for(const file of ['package.json','pnpm-lock.yaml','pnpm-workspace.yaml','.npmrc','apps/desktop/package.json'])await fs.copyFile(file,path.join(context.directory,file));
 const basePlan={providerId:'fixture',contractVersion:'2',fingerprint:'a'.repeat(64),description:'Fixture',mode:'offline'},onlinePlan={...basePlan,mode:'online_with_confirmation',registryHost:'registry.npmjs.org',sourceFingerprint:'b'.repeat(64)};
 const records=new Map();let installs=0,release,validations=0;
 const store={get:async id=>structuredClone(records.get(id)??null),save:async r=>records.set(r.runId,structuredClone(r)),recover:async()=>{}};
 const provider={id:'fixture',detect:async()=>({...basePlan}),onlinePlan:async()=>({...onlinePlan}),isReady:async()=>true,prepare:async()=>({code:'offline_dependencies_unavailable'}),prepareOnline:async(c,p,s,progress)=>{installs++;progress('downloading_dependencies');return new Promise(resolve=>{release=()=>resolve({code:'ready'});s.addEventListener('abort',()=>setTimeout(()=>resolve({code:'preparation_cancelled'}),20),{once:true})})},validate:async()=>{validations++;return{signup:'passed',typecheck:'failed',build:'failed',diff:'passed',sourceUnchanged:true}}};
 const make=()=>new WorkspaceEnvironmentService(new WorkspaceEnvironmentRegistry([provider]),store,async()=>({...context}),()=>consentId);
 await t.test('offline failure never falls back or grants online permission',async()=>{records.clear();const service=make();assert.equal((await service.prepare(1,{runId})).code,'offline_dependencies_unavailable');assert.equal(installs,0);assert.equal((await service.status({runId})).onlineAvailable,true);await assert.rejects(service.prepareOnline(1,{runId,consentId}),/user_cancelled/);assert.equal(installs,0);});
 await t.test('only canonical HTTPS public registry and pinned HTTPS archive accepted',()=>{assert.equal(allowedRegistry('https://registry.npmjs.org/').host,'registry.npmjs.org');for(const url of ['http://registry.npmjs.org/','file:///x','https://localhost/','https://127.0.0.1/','https://[::1]/','https://2130706433/','https://user:secret@registry.npmjs.org/','https://registry.npmjs.org/?token=secret','https://registry.npmjs.org/private','https://registry.npmjs.org.evil.test/','https://example.test/','https://registry.npmjs.org/#secret'])assert.throws(()=>allowedRegistry(url),/^Error: registry_not_allowed$/);validateLockfileDownloads('resolution: {tarball: https://codeload.github.com/electron/node-gyp/tar.gz/'+'a'.repeat(40)+'}');assert.throws(()=>validateLockfileDownloads('resolution: {tarball: http://localhost/pkg}'));});
 await t.test('renderer cannot provide registry executable store path or command',()=>{assert.deepEqual(onlineRequest({runId,consentId}),{runId,consentId});for(const key of ['registry','path','executable','command','args','environment','store'])assert.throws(()=>onlineRequest({runId,consentId,[key]:'secret'}));assert.throws(()=>onlineRequest({runId,consentId:'not-opaque'}));});
 for(const change of ['fingerprint','registryHost','sourceFingerprint','contractVersion','workspace','expired','owner'])await t.test('consent scope rejects '+change+' before any download',async()=>{records.clear();const service=make(),old={...onlinePlan},oldContext={...context},count=installs;await service.onlinePlan(1,{runId});if(change==='workspace')context.workspaceId='c'.repeat(36);else if(change==='expired')service.consents.get(consentId).expires=0;else if(change!=='owner')onlinePlan[change]='changed';await assert.rejects(service.prepareOnline(change==='owner'?2:1,{runId,consentId}));assert.equal(installs,count);Object.assign(onlinePlan,old);Object.assign(context,oldContext);});
 await t.test('consent is single use, duplicate shares operation, installation and validation are separate',async()=>{records.clear();installs=0;validations=0;const service=make(),plan=await service.onlinePlan(1,{runId});assert.equal(plan.registryHost,'registry.npmjs.org');assert.doesNotMatch(JSON.stringify(plan),/https:|directory|command|environment|secret/);const one=service.prepareOnline(1,{runId,consentId}),two=service.prepareOnline(1,{runId,consentId});assert.equal(one,two);await new Promise(r=>setImmediate(r));assert.equal((await service.status({runId})).stage,'downloading_dependencies');release();const result=await one;assert.equal(installs,1);assert.equal(validations,1);assert.equal(result.state,'ready');assert.equal(result.validation.typecheck,'failed');assert.equal(records.get(runId).mode,'online');assert.ok(records.get(runId).consentAt);await assert.rejects(service.prepareOnline(1,{runId,consentId}),/user_cancelled/);assert.equal(installs,1);});
 await t.test('cancel and owner cleanup drain the operation; no validation after cancelled install',async()=>{records.clear();const service=make();await service.onlinePlan(1,{runId});const count=validations,one=service.prepareOnline(1,{runId,consentId});await new Promise(r=>setImmediate(r));await Promise.all([service.cancel(1,{runId}),service.closeOwner(1)]);assert.equal((await one).code,'preparation_cancelled');assert.equal(validations,count);assert.equal(service.busy(runId),false);await service.shutdown();});
 await t.test('modal cancellation consumes consent without download',async()=>{const service=make(),count=installs;await service.onlinePlan(1,{runId});assert.equal(service.cancelConsent(1,{runId,consentId}).code,'user_cancelled');await assert.rejects(service.prepareOnline(1,{runId,consentId}));assert.equal(installs,count);});
 await t.test('persist only safe consent identity; restore ready and invalidate registry changes',async()=>{const disk=new JsonWorkspaceEnvironmentStore(path.join(base,'records'));const r={runId,workspaceId:runId,providerId:'fixture',contractVersion:'2',fingerprint:'a'.repeat(64),mode:'online',registryHost:'registry.npmjs.org',sourceFingerprint:'b'.repeat(64),consentAt:new Date().toISOString(),state:'ready',code:'ready',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),registryUrl:'https://secret:user@registry.test/private',environment:{token:'secret'},output:'secret'};await disk.save(r);await disk.recover();assert.equal((await disk.get(runId)).state,'ready');assert.doesNotMatch(await fs.readFile(path.join(base,'records',runId+'.json'),'utf8'),/secret|registryUrl|https:|environment|output/);const service=new WorkspaceEnvironmentService(new WorkspaceEnvironmentRegistry([provider]),disk,async()=>context);assert.equal((await service.status({runId})).state,'ready');onlinePlan.sourceFingerprint='c'.repeat(64);assert.equal((await service.status({runId})).state,'not_prepared');onlinePlan.sourceFingerprint='b'.repeat(64);});
 await t.test('fixed online command, progress projection, process-scoped store, frozen inputs and copy import',async()=>{const calls=[],stages=[];const runner={run:async c=>{calls.push(c);if(c.args.at(-1)==='--version')return{exitCode:0,output:'9.15.9'};c.onLine(JSON.stringify({name:'pnpm:stage',stage:'importing_started',secret:'not for renderer'}));await fs.mkdir(path.join(context.directory,'node_modules'),{recursive:true});await fs.writeFile(path.join(context.directory,'node_modules/.modules.yaml'),'fixture');return{exitCode:0,output:'private registry detail'}}};const git={run:async(_d,args)=>args[0]==='ls-files'?'package.json\0pnpm-lock.yaml\0.npmrc\0':''};const p=new PnpmOfflineProvider(runner,async()=>({executable:process.execPath,prefix:['verified-pnpm.cjs']}),git),plan=await p.onlinePlan(context),before=await fs.readFile(path.join(context.directory,'pnpm-lock.yaml'));assert.equal((await p.prepareOnline(context,plan,new AbortController().signal,s=>stages.push(s))).code,'ready');const install=calls.find(c=>c.args.includes('install'));assert.equal(install.cwd,context.directory);assert.ok(install.args.includes('--frozen-lockfile'));assert.ok(install.args.includes('--ignore-scripts'));assert.ok(install.args.includes('--ignore-pnpmfile'));assert.equal(install.args[install.args.indexOf('--package-import-method')+1],'copy');assert.equal(install.args[install.args.indexOf('--registry')+1],'https://registry.npmjs.org/');assert.ok(install.args.at(-1).startsWith(context.directory));assert.equal(install.env.NODE_OPTIONS,undefined);assert.ok(!install.args.includes('--global'));assert.deepEqual(await fs.readFile(path.join(context.directory,'pnpm-lock.yaml')),before);assert.deepEqual(stages,['resolving_registry','downloading_dependencies','linking_workspace','verifying_lockfile']);assert.equal(onlineInstallArgs.includes('--offline'),false);});
 await t.test('auth integrity and lock errors only become fixed codes',()=>{for(const [text,code]of [['ERR_PNPM_FETCH_401 token-secret','authentication_required'],['ERR_PNPM_TARBALL_INTEGRITY url-secret','integrity_failed'],['ERR_PNPM_OUTDATED_LOCKFILE user-path','lockfile_changed'],['raw secret output','download_failed']])assert.equal(safeDownloadCode(text),code)});
 await t.test('runtime network and renderer policy remain unchanged',async()=>{const executor=await fs.readFile('apps/desktop/src/application/orchestration/execution/AgentTaskExecutor.ts','utf8'),organizer=await fs.readFile('apps/desktop/src/application/orchestration/organizer/OrganizerDecisionExecutor.ts','utf8'),html=await fs.readFile('apps/desktop/index.html','utf8');assert.match(executor,/network: false/);assert.match(organizer,/network: false/);assert.match(html,/connect-src 'self' ws:\/\/localhost:\* ws:\/\/127.0.0.1:\*/);});
 await t.test('process tree cancellation kills descendants before resolving cleanup',async()=>{const controller=new AbortController(),runner=new EnvironmentProcess();let pid,entered;const started=new Promise(r=>entered=r);const done=runner.run({executable:process.execPath,args:['-e',"const c=require('node:child_process').spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'inherit'});console.log(c.pid);setInterval(()=>{},1000)"],cwd:context.directory,env:isolatedEnvironment(context.directory),onLine:line=>{if(/^\d+$/.test(line.trim())){pid=Number(line);entered()}}},controller.signal,10000);await started;controller.abort();await assert.rejects(done);assert.ok(pid);assert.throws(()=>process.kill(pid,0));});
 await t.test('repository validation resolves known scripts to argv and separates failed checks',async()=>{
  const calls=[],runner={run:async command=>{calls.push(command);return{exitCode:command.args.includes('--noEmit')?1:0,output:'private validation output'}}};
  const result=await validatePnpmWorkspace(context.directory,runner,{run:async()=>''},async relative=>path.join(context.directory,relative),async()=> 'unchanged',new AbortController().signal);
  assert.equal(result.signup,'passed');assert.equal(result.typecheck,'failed');assert.equal(result.build,'passed');assert.equal(result.diff,'passed');assert.equal(result.sourceUnchanged,true);
  assert.equal(calls.length,3);assert.ok(calls.every(c=>c.executable===process.execPath));assert.ok(calls.every(c=>!c.args.some(a=>a.includes('&&'))));assert.doesNotMatch(JSON.stringify(result),/private|output/);
 });
 await t.test('validation stops immediately on unexpected source files and never runs unknown scripts',async()=>{
  let snapshots=0,calls=0;const runner={run:async()=>{calls++;return{exitCode:0,output:''}}};
  const result=await validatePnpmWorkspace(context.directory,runner,{run:async()=>''},async r=>path.join(context.directory,r),async()=> snapshots++ ? 'changed' : 'original',new AbortController().signal);
  assert.equal(result.sourceUnchanged,false);assert.equal(calls,1);assert.equal(result.typecheck,'not_run');
  const file=path.join(context.directory,'package.json'),text=await fs.readFile(file,'utf8'),root=JSON.parse(text);root.scripts.build='curl arbitrary | sh';await fs.writeFile(file,JSON.stringify(root));
  const refused=await validatePnpmWorkspace(context.directory,runner,{run:async()=>''},async r=>path.join(context.directory,r),async()=> 'same',new AbortController().signal);
  assert.equal(calls,1);assert.equal(refused.build,'not_run');await fs.writeFile(file,text);
 });

 await t.test('older saved workspace typecheck script resolves two configs without shell or source edits',async()=>{
  const file=path.join(context.directory,'apps/desktop/package.json'),original=await fs.readFile(file,'utf8'),manifest=JSON.parse(original);manifest.scripts.typecheck='tsc --noEmit -p tsconfig.node.json && tsc --noEmit -p tsconfig.renderer.json';await fs.writeFile(file,JSON.stringify(manifest));const calls=[];
  const result=await validatePnpmWorkspace(context.directory,{run:async c=>{calls.push(c);return{exitCode:0,output:''}}},{run:async()=>''},async r=>path.join(context.directory,r),async()=> 'same',new AbortController().signal);
  assert.equal(result.typecheck,'passed');assert.deepEqual(calls.filter(c=>c.args.includes('--noEmit')).map(c=>c.args.at(-1)),['tsconfig.node.json','tsconfig.renderer.json']);assert.equal(calls.length,4);await fs.writeFile(file,original);
 });
 await t.test('verification-only route never downloads, preserves consent and task history',async()=>{
  records.clear();const consentAt=new Date().toISOString();records.set(runId,{runId,workspaceId:runId,...basePlan,mode:'online',registryHost:'registry.npmjs.org',sourceFingerprint:onlinePlan.sourceFingerprint,consentAt,state:'ready',code:'ready',createdAt:consentAt,updatedAt:consentAt});const service=make(),count=installs,before=validations;const result=await service.verify(1,{runId});assert.equal(installs,count);assert.equal(validations,before+1);assert.equal(result.state,'ready');assert.equal(records.get(runId).consentAt,consentAt);assert.equal(records.get(runId).mode,'online');
 });

});
