import { TeamOrganizerField } from './TeamOrganizerField';
import type { TeamDefinition } from '../../../shared/management-api';
import { useTeamEditor } from '../../hooks/useTeamEditor';
import { useAgentManagement } from '../../state/ManagementContext';
import { TeamMemberList } from './TeamMemberList';
import { AvailableAgentList } from './AvailableAgentList';
export function TeamEditor({ team }: { team?: TeamDefinition }) {
 const editor = useTeamEditor(team); const { agents, loading, error } = useAgentManagement();
 return <section className="management-editor-screen"><button type="button" className="back-button" disabled={editor.saving} onClick={editor.cancel}>‹ Teams</button><header className="record-editor-header"><div><h1>{team?.name ?? 'New team'}</h1><p>Team configuration</p></div></header><form className="agent-editor" onSubmit={event => { event.preventDefault(); void editor.submit(); }}><fieldset disabled={editor.saving || loading}><div className="agent-field-group"><label>Team name<input required maxLength={100} value={editor.draft.name} onChange={event => editor.change({ name: event.target.value })} /></label><label>Description<textarea rows={2} maxLength={10000} value={editor.draft.description} onChange={event => editor.change({ description: event.target.value })} /></label></div><TeamOrganizerField members={editor.draft.agentIds.flatMap(id => { const agent = agents.find(item => item.id === id); return agent ? [agent] : []; })} organizerAgentId={editor.draft.organizerAgentId} onChange={organizerAgentId => editor.change({ organizerAgentId })} /><TeamMemberList ids={editor.draft.agentIds} organizerAgentId={editor.draft.organizerAgentId} agents={agents} onChange={agentIds => editor.change({ agentIds })} /><AvailableAgentList agents={agents.filter(agent => !editor.draft.agentIds.includes(agent.id))} onAdd={id => { if (!editor.draft.agentIds.includes(id)) editor.change({ agentIds: [...editor.draft.agentIds, id] }); }} /></fieldset>{(editor.error || error) && <p role="alert" className="workspace-error">{editor.error ?? error}</p>}<footer className="agent-editor-actions"><button type="button" className="agent-button" disabled={editor.saving} onClick={editor.cancel}>Cancel</button><button type="submit" className="agent-button agent-button-primary" disabled={editor.saving || loading || !editor.draft.name.trim() || (editor.draft.agentIds.length < 2 || !editor.draft.organizerAgentId || !editor.draft.agentIds.includes(editor.draft.organizerAgentId)) || Boolean(team && !editor.dirty)}>{editor.saving ? 'Saving…' : team ? 'Save changes' : 'Create team'}</button></footer></form></section>;
}
